controllers/backend/gateway/gateway_controller.go, pkg/data/data.go
Don't set LB to zero ports.
Try hostname == "localhost" as 127.0.0.1
=> Fix service LB issues

scripts/validate, tests/run/run-cap-drop.bats, tests/run/run-env-value.bats, tests/validation/config.bats, tests/validation/create.bats, tests/validation/export.bats, tests/validation/run.bats, tests/validation/scale.bats, tests/validation/service-mesh.bats, tests/validation/stack.bats, tests/validation/stage.bats, tests/validation/volume.bats
Adding environment variable test
Changing double [ to single in validation
=> automated tests check-in

tests/run/run-cap-add.bats, tests/run/run-cap-drop.bats, tests/run/run-config.bats, tests/run/run-env-value.bats, tests/validation/config.bats, tests/validation/run.bats, tests/validation/scale.bats, tests/validation/stack.bats, tests/validation/volume.bats
Added : run --config tests
Updated : run -e test
Updates:  titles for validation tests
=> run tests and update validation

tests/run/run-image-pull.bats, tests/run/run-label-file.bats, tests/run/run-label.bats, tests/run/run-memory-limit.bats, tests/run/run-memory.bats, tests/run/run-metadata.bats, tests/run/run-scale.bats, tests/validation/volume.bats
image-pull
label-file
label
volume
memory-limit
=> New run tests

tests/run/run-cap-add.bats, tests/run/run-cap-drop.bats, tests/run/run-config.bats, tests/run/run-cpus.bats, tests/run/run-dns-option.bats, tests/run/run-dns-search.bats, tests/run/run-dns.bats, tests/run/run-image-pull.bats, tests/run/run-label-file.bats, tests/run/run-label.bats, tests/validation/config.bats, tests/validation/create.bats, tests/validation/export.bats, tests/validation/run.bats, tests/validation/scale.bats, tests/validation/stack.bats, tests/validation/volume.bats
optimize current tests
Add new run tests
=> optimize tests and add new tests

tests/conftest.py, tests/util.py, tests/validation/config.py, tests/validation/create.py, tests/validation/export.py, tests/validation/run.py, tests/validation/scale.py, tests/validation/stack.py
Tests:
config
create
export
run
scale
stack
=> validation tests for pytest

agent/main.go
https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#network-plugin-requirements
=> always set bridge-nf-call-iptables to 1

README.md
I hope this is helpful. No content changes, just grammar improvements.
=> Bunch of typo and grammar improvements

install.sh
I ran the install script through shellcheck and fixed everything apart
from line 46.
```
In install.sh line 46:
OS=$(echo "$(uname)"|tr '[:upper:]' '[:lower:]')
^--------^ SC2005: Useless echo? Instead of 'echo $(cmd)', just use 'cmd'.
```
=> Ran install.sh through shellcheck

cli/cmd/create/health.go, cli/cmd/externalservice/create.go, cli/cmd/install/install.go, cli/pkg/pretty/objectmappers/strings_match.go, cli/pkg/table/writer.go, cli/pkg/tables/externalservice.go, cli/pkg/tables/router.go, modules/istio/controllers/istio/controller.go, modules/istio/controllers/routeset/populate/virtualservice.go, pkg/apis/rio.cattle.io/v1/router.go, pkg/pretty/stringers/data_mount.go, pkg/pretty/stringers/env.go, pkg/pretty/stringers/permission.go
This commit rewrite some if-else chains to switch statements.
Based on Go style guide:
https://golang.org/doc/effective_go.html#switch
=> Rewrite some if-else chains to switch statements

README.md
Typing 'simply' isn't simple ;)
=> Fix 'simply' typo

cli/cmd/create/create.go, modules/service/controllers/service/populate/pod/podspec.go, pkg/apis/rio.cattle.io/v1/service_types.go, pkg/riofile/mappers/hostnetwork.go, pkg/riofile/riofile.go, pkg/riofile/schema.go
https://github.com/rancher/rio/issues/343
=> Add hostnetworking support

modules/service/controllers/clusterdomain/clusterdomain.go
issue: https://github.com/rancher/rio/issues/469
=> Get clusterDomain if not found in cache

cli/cmd/create/create.go, cli/cmd/create/timeout.go, modules/build/controllers/service/service.go, pkg/apis/rio.cattle.io/v1/service_types.go, pkg/apis/rio.cattle.io/v1/zz_generated_deepcopy.go
Addresses https://github.com/rancher/rio/issues/418
=> Add timeout option to build parameters

modules/build/controllers/proxy/controller.go
For local registry we previously use hostport to expose registry service
to localhost:5442. Since hostports are wonky and won't work in every k8s
distro, switching to socat container with hostNetwork: true would be the
best solution
=> Only deploy socat with hostNetwork to proxy registry

docs/README.md, modules/istio/features/routing/feature.go, modules/linkerd/feature/feature.go
Issue: https://github.com/rancher/rio/issues/512
=> Doc changes for v0.5.0

docs/README.md
Issue: https://github.com/rancher/rio/issues/512
=> README update: route insert is a flag on add, not standalone

pkg/stack/stack.go
Addresses https://github.com/rancher/rio/issues/432
=> Add ability to provide imagePath in Riofile

Dockerfile.dapper, tests/integration/config_test.go, tests/integration/run_test.go, tests/testutil/config.go, tests/testutil/service.go, tests/testutil/testutil.go
Beginning of validations for Issue #559 
This creates the kubectl wrapper and a couple of simple tests using it
=> Add wrapper for kubectl

tests/integration/domain_test.go, tests/integration/riofile_test.go, tests/integration/route_test.go, tests/integration/weight_test.go, tests/testutil/publicdomain.go, tests/testutil/router.go, tests/testutil/service.go
Issue: #559 
Summary of PR:
Add another useful test for routes
Add kubectl validations for domain, weight, and route tests
=> Add route test and kubectl validations

tests/integration/scale_test.go, tests/testutil/service.go, tests/testutil/testutil.go
This is part of #559 Add kubectl validations to the test framework
=> Adding validations to scale tests

tests/testutil/testutil.go
This is the default rio/kubectl behavior, we should do the same for the client-go
=> Falling back to default ~/.kube/config if no KUBECONFIG env is set for client-go

install.sh
When you're on slow or flakey internet, some visual indicator of progress, and "time left [til happiness]" is a Good Thing.
=> installer - show progress of download of 70M+ rio binary

cli/cmd/promote/promote.go, cli/cmd/weight/weight.go, go.mod, go.sum, modules/service/controllers/rollout/controller.go, tests/integration/endpoint_test.go, tests/integration/suite_test.go, tests/integration/weight_test.go, tests/testutil/service.go, tests/validation/weight_test.go, vendor/github.com/rancher/norman/pkg/types/reflection.go, vendor/modules.txt
depends on: https://github.com/rancher/norman/pull/315
This will fix: #577, #496
Also includes some fixes for rolloutController bugs
=> Duration to string fixes cli and tests

tests/integration/stage_test.go, tests/integration/suite_test.go, tests/testutil/service.go
Tests for: https://github.com/rancher/rio/pull/646
=> Adds stage specific tests

cli/cmd/create/create.go, cli/cmd/util/service.go, modules/service/controllers/rollout/controller.go, tests/integration/run_test.go
Issue: https://github.com/rancher/rio/issues/652
=> Dont ever weight template svcs

cli/cmd/stage/stage.go
issue: https://github.com/rancher/rio/issues/650
=> adds env param to stage

cli/cmd/stage/stage.go
=> interactive stage inherits app if not explicitly sepcified

tests/Dockerfile, tests/entrypoint.sh, tests/integration/attach_test.go, tests/integration/endpoint_test.go, tests/integration/log_test.go, tests/integration/rbac_test.go, tests/integration/run_test.go, tests/integration/scale_test.go, tests/integration/suite_test.go, tests/testutil/service.go, tests/testutil/testutil.go, tests/validation/autoscale_test.go, tests/validation/weight_test.go
=> Add attach and log tests and update service readystate check

cli/cmd/publicdomain/add.go, cli/cmd/publicdomain/publicdomain.go, cli/pkg/tables/publicdomain.go, modules/gloo/controller/ingress/handler.go, pkg/indexes/indexes.go
Fix regression bug that were introduced in api refactoring
=> Fix public domain bug round 3

cli/cmd/export/export.go, pkg/riofile/riofile.go, tests/integration/fixtures/riofile-export.yaml, tests/integration/riofile_test.go, tests/testutil/riofile.go
Issue: https://github.com/rancher/rio/issues/641
=> Enable export of stack by gvk

cli/cmd/ps/ps_services.go
Issue: https://github.com/rancher/rio/issues/739
Weight calc on ps was summing on app string, but app string can be blank and it was counting those as the same app.
=> Show svc weight as 100 if app blank

cli/pkg/tables/service.go
=> Shows user why endpoint is missing

cli/cmd/weight/weight.go, tests/integration/endpoint_test.go, tests/integration/route_test.go, tests/integration/stage_test.go, tests/integration/weight_test.go, tests/testutil/service.go, tests/testutil/testutil.go
Hopefully this helps with flakiness...
=> Add some simple retry to service rio commands

cli/cmd/externalservice/create.go, cli/cmd/externalservice/externalservice.go, modules/service/controllers/externalservice/populate/populate.go, tests/integration/externalservice_test.go, tests/testutil/externalservice.go
related issue: https://github.com/rancher/rio/issues/775
=> Fix external service bug

cli/cmd/logs/logs.go, cli/cmd/util/pods.go, go.mod, go.sum, vendor/github.com/wercker/stern/stern/config.go, vendor/github.com/wercker/stern/stern/container_state.go, vendor/github.com/wercker/stern/stern/main.go, vendor/github.com/wercker/stern/stern/watch.go, vendor/modules.txt
Issue: https://github.com/rancher/rio/issues/782
Depends on: https://github.com/rancher/stern/pull/3
=> Log cmd targets build pods correctly

cli/cmd/install/install.go
issue: https://github.com/rancher/rio/issues/783
=> Warn on unsupported kubernetes versions

cli/cmd/install/install.go
issue: https://github.com/rancher/rio/issues/783
=> only display k8s version warning once

go.mod, go.sum, vendor/github.com/rancher/norman/pkg/types/mapper/set_value.go
Fix for: https://github.com/rancher/rio/issues/532#issuecomment-553183773
=> Upgrade Norman to fix riofile nil panics

cli/cmd/secrets/create.go
Add annotation and url prompt. Tekton requires special annotations
to add ssh-key
=> Fix git-ssh secrets create in CLI

cli/cmd/install/install.go
related issue: https://github.com/rancher/rio/issues/800
=> Fix install shouldn't check disabledFeatures

docs/v0.6.0/cli-reference.md, docs/v0.6.0/install.md
This will finish docs for https://github.com/rancher/rio/issues/671 and https://github.com/rancher/rio/issues/511 and https://github.com/rancher/rio/issues/561
=> Adds cloud provider doc notes

cli/cmd/stage/stage.go, modules/service/controllers/rollout/controller.go
Follow up to https://github.com/rancher/rio/issues/719
Run/weight/stage should also set default weight to 10,000. Stage was still using 100.
=> Stage uses promoteWeight for weight, as run does

cli/cmd/logs/logs.go
https://github.com/rancher/rio/issues/708
https://github.com/rancher/rio/issues/772
=> Error on zero-scaled service and allow logging after pod deletion

cli/cmd/logs/logs.go, go.mod, go.sum, vendor/github.com/wercker/stern/stern/main.go, vendor/github.com/wercker/stern/stern/tail.go, vendor/modules.txt
See: https://github.com/rancher/stern/commit/d38af544c2e65088d5aeb4f6537e655fad5a3cb9
Issue: https://github.com/rancher/rio/issues/772
=> Cleanup failed tails and replace with working ones

cli/pkg/localbuilder/runc/containerd.go, cli/pkg/up/build.go
Part of https://github.com/rancher/rio/issues/864
=> Build should pass dockerfile name

cli/cmd/up/up.go, docs/riofile.md
Follow up to https://github.com/rancher/rio/pull/895
Issue: https://github.com/rancher/rio/issues/894
=> Revision var

cli/cmd/builds/build.go, cli/pkg/up/build.go
Issue: https://github.com/rancher/rio/issues/896
=> rio build should handle absolute paths

cli/cmd/uninstall/uninstall.go
This further verifies that the cluster roles being deleted belong to Rio
services 
Addresses https://github.com/rancher/rio/issues/613
=> Add validation to cluster level RBAC uninstall

modules/build/controllers/build/controller.go, modules/build/controllers/service/service.go
Issue: https://github.com/rancher/rio/issues/918
=> allow user to specify custom build tag

go.mod, go.sum, vendor/github.com/sclevine/spec/.travis.yml, vendor/github.com/sclevine/spec/go.mod, vendor/github.com/sclevine/spec/spec.go, vendor/modules.txt
See: https://github.com/sclevine/spec/pull/14#issuecomment-565198729
=> bump spec to 1.4

cli/cmd/create/build.go, cli/cmd/up/up.go, modules/build/controllers/gitcommit/service.go, modules/service/controllers/template/handler.go
=> Pr from non template service

modules/service/controllers/template/handler.go
Issue: https://github.com/rancher/rio/issues/924#issuecomment-566673835
=> New template service gets standard weight

cli/cmd/create/build.go
=> Disable non-template and pr mode together.

cli/cmd/create/create.go, cli/cmd/promote/promote.go, cli/cmd/ps/ps_services.go, cli/cmd/stage/stage.go, cli/cmd/util/service.go, cli/cmd/weight/weight.go, docs/cli-reference.md, modules/service/controllers/template/handler.go, pkg/apis/rio.cattle.io/v1/service_types.go, pkg/apis/rio.cattle.io/v1/zz_generated_deepcopy.go, pkg/services/weight.go, pkg/services/weight_test.go, tests/integration/run_test.go, tests/integration/stage_test.go, tests/testutil/service.go
issue: https://github.com/rancher/rio/issues/924
=> Move weight logic to pgk to allow template rollout

modules/gloo/pkg/vsfactory/target.go, tests/testutil/service.go
Follow up to: https://github.com/rancher/rio/issues/924
=> Weight target rc req

pkg/constants/constants.go
https://github.com/rancher/rio/issues/977
=> Update to linkerd 2.6.1

.github/ISSUE_TEMPLATE/bug_report.md, cli/cmd/secrets/create.go
#954 
Also update bug template to use comments to that submitted bugs are cleaner
=> Add option to specify secret name

README.md
=> Update copyright date in `README.md`
