- vagrant.yaml
> Fix vagrant.yaml default rio version

- pkg/clientaccess/clientaccess.go
getCacert will return empty if cacerts is trusted by system certs. Don't
compare the hash if cacerts is trusted(in case it is proxyed through
ngrok)
> don't compare hash if cacert is empty

- cli/pkg/clicontext/config.go
The auth plugin package for GCP isn't included not allowing Rio to be installed to GKE clusters. #234 
Vendor packaging needs to be updated - unsure if this should be done as part of commit.
> Import the auth plugin package for gcp

- modules/service/controllers/service/populate/pod/containers.go
Removed "value" parameter from EnvVar passed onto K8S
> Remove "value" parameter from EnvVar when using config:// or secret:// as --env parameter

- README.md
Updates README.md to mention that Rio is in alpha so it's more clear to end-users.
> Update README to mention alpha

- docs/README.md
Specifically, I added details on confirming that `rio` generates the correct secret, and then how to use that secret to authenticate against the Docker registry when pulling the image.
> Add details on working with private docker repo

- cli/cmd/revision/revision.go
Fixes #413 
Matched default formatting to rio ps -q format (< ns >/< app-name >:< version >)
```
PS C:\Users\charm\go\src\github.com\charm-jp\rio\bin> .\rio.exe ps -q
default/demo1
```
```
PS C:\Users\charm\go\src\github.com\charm-jp\rio\bin> .\rio.exe revision
NAME               IMAGE                    CREATED          SCALE     ENDPOINT                                    WEIGHT    DETAIL
default/demo1:v3   ibuildthecloud/demo:v3   15 minutes ago   1         https://demo1-v3-default.7u4m7x.on-rio.io   0
default/demo1:v0   ibuildthecloud/demo:v1   16 minutes ago   1         https://demo1-v0-default.7u4m7x.on-rio.io   100
```
```
PS C:\Users\charm\go\src\github.com\charm-jp\rio\bin> .\rio.exe revision -q
default/demo1:v3
default/demo1:v0
```
> revision -q fix

- pkg/pretty/stringers/env.go
Fixes #425 
Created secret:
```
apiVersion: v1
kind: Secret
metadata:
name: test
type: Opaque
data:
secval: YWRtaW4=
```
Test:
```
rio run -p 80/http --env TEST=secret://test/secval --name demo1 ibuildthecloud/demo:v1
default/demo1:v0
rio.exe edit default/demo1:v0
```
Result Contents:
```
concurrency: 10
env:
- TEST=secret://test/secval
image: ibuildthecloud/demo:v1
imagePullPolicy: IfNotPresent
ports:
- "80"
rollout: true
rolloutIncrement: 5
rolloutInterval: 5
scale: 1-10
weight: 100
```
> Edit config with env secret:// or config:// set

- cli/pkg/clicontext/types.go
Issue: https://github.com/rancher/rio/issues/422
This assumes that the CLI should never display these types of secrets.
* Install rio
* run `rio secret` and notice lots of secrets
* use new CLI build with same cluster and notice `rio secret` no longer lists secrets with type `kubernetes.io/service-account-token` or type `istio.io/key-and-cert`
> Limit secret list by type

- modules/build/feature/feature.go
This fixes the _"no available registry endpoint: failed to do request: Head http://localhost:5442"_ error
> Ensure registry proxy is starting

- cli/main.go
This commit add support for printing out the help for a specific
subcommand when a commands matching the form rio SUBCOMMAND --help
are entered.
Addresses https://github.com/rancher/rio/issues/491
> Print subcommand help 

- cli/cmd/export/export.go
- cli/cmd/rm/rm.go
Issue: https://github.com/rancher/rio/issues/551
We are adding the memory address of iterator `obj` twice, but then re-setting obj on loop so you get multiple of the same. Fix is to use address of actual value, not the iterator. 
Will add testing for this in the export roundtrip issues. 
Also add stack to rm types in CLI
> Fix bug to allow riofile export to have multiples

- tests/testutil/config.go
- tests/testutil/externalservice.go
- tests/testutil/publicdomain.go
- tests/testutil/router.go
- tests/testutil/service.go
- tests/testutil/testutil.go
Follow up to https://github.com/rancher/rio/issues/486 to remove flakiness 
Reuse poll to make life easier: https://godoc.org/k8s.io/apimachinery/pkg/util/wait#Poll
> Use k8s wait method and scale wait times to remove flakiness

- scripts/test
- tests/README.md
- tests/integration/export_test.go
- tests/integration/fixtures/riofile-export.yaml
- tests/integration/riofile_test.go
- tests/integration/suite_test.go
- tests/testutil/config.go
- tests/testutil/externalservice.go
- tests/testutil/publicdomain.go
- tests/testutil/riofile.go
- tests/testutil/router.go
- tests/testutil/service.go
- tests/testutil/testutil.go
Issue: https://github.com/rancher/rio/issues/532
This PR does multiple things: 
* Add roundtrip integration tests for riofile including endpoint checks and export checks
* Convert RioCMD signature arguments to a single slice. 
* Fail any CI run that includes `.Focus()`
> Add roundtrip stack export integration test

- tests/integration/endpoint_test.go
- tests/integration/riofile_test.go
- tests/testutil/service.go
- tests/testutil/testutil.go
This validates the endpoint URLs generated by rio for the revisions and not versioned are present.
https://github.com/rancher/rio/issues/559
> Adding extra validations using kubectl for service endpoints

- scripts/ci
Linter and code formatting errors should happen earlier before tests are executed.
> Reordering the validations in CI

- Dockerfile.dapper
We no longer use python for test execution on CI
> Removing unused python dependencies from CI Dockerfile

- Dockerfile.dapper
- tests/README.md
- tests/integration/domain_test.go
- tests/integration/endpoint_test.go
- tests/integration/riofile_test.go
- tests/integration/run_test.go
- tests/integration/scale_test.go
- tests/integration/suite_test.go
- tests/integration/weight_test.go
- tests/testutil/service.go
- tests/testutil/testutil.go
- tests/validation/autoscale_test.go
- tests/validation/suite_test.go
- tests/validation/weight_test.go
Issue: #570 
This covers the first scenario from the P1 Rio Run Test Cases.
Some changes had to be made to the test framework to accommodate this. The three I'd like to highlight are:
- Installing the "hey" tool into CI to generate load on the endpoitns
- Removing the port from `service.Create()` and adding optional arguments to it. The port should be used as an argument in many cases, but not all. There are also additional run options that are important to test, so having the optional arguments will give us this ability.
-  Added this check in `waitForReadyService()`: `ts.Service.Status.DeploymentStatus.AvailableReplicas == ts.Service.Status.DeploymentStatus.Replicas`. This one I'm not convinced about, but want to get others' feedback. I think it might be better to have a …
> Add P1 tests to integration and validation

- install.sh
Allows installation of `rio` into a directory that doesn't require `sudo` for installation by manually passing `SKIP_SUDO=1`.
Usage:
```
SKIP_SUDO=1 INSTALL_RIO_BIN_DIR=$PWD ./install.sh
```
Or give it a try with:
```
export SKIP_SUDO=1
export INSTALL_RIO_BIN_DIR=$PWD 
curl -sfL https://raw.githubusercontent.com/drnic/rio/installer-skip-sudo/install.sh | sh -
```
> installer.sh - allow install binary without requiring sudo

- Dockerfile.dapper
- tests/integration/externalservice_test.go
- tests/integration/riofile_test.go
- tests/testutil/externalservice.go
This is part of #559 Add kubectl validations to the test framework
> Adding kube validations for externalservices

- tests/validation/scale_test.go
- tests/validation/suite_test.go
```bash
=== RUN   TestSuite
Suite: validation suite
Total: 3 | Focused: 1 | Pending: 0
Focus is active.
=== RUN   TestSuite/validation_suite
=== RUN   TestSuite/validation_suite/scale/scale_is_called_on_a_service/should_scale_to_11
=== PAUSE TestSuite/validation_suite/scale/scale_is_called_on_a_service/should_scale_to_11
=== RUN   TestSuite/validation_suite/autoscale/run_a_service_with_minscale_of_0/should_autoscale_down_to_0
=== RUN   TestSuite/validation_suite/weight/a_staged_service_incrementally_rolls_out_weight/should_slowly_increase_weight_on_the_staged_service_and_decrease_current_service_weight
=== CONT  TestSuite/validation_suite/scale/scale_is_called_on_a_service/should_scale_to_11
Passed: 1 | Failed: 0 | Skipped: 2
--- PASS: TestSuite (218.10s)
--- PASS: …
```
> Moving Scale to 11 test to the validation test suite

- tests/Dockerfile
- tests/entrypoint.sh
Added a docker build for tests to run integration or validation tests so that these can be run easily in any environment. 
Note that this expects a released/pre-release version of rio. 
For local development, you will need to add to the Dockerfile to copy your local rio cli binary.
**Example Local Run**
1. Add a KUBECONFIG file to `/path/to/rio/.kube/config`
2. Make sure you have docker installed, then run the following in a terminal:
```
docker build -f "/path/to/rio/tests/Dockerfile" -t rio-test /path/to/rio
docker run --rm -e test=integration rio-test:latest
docker run --rm -e test=validation rio-test:latest
docker run --rm -e test=integration -e INSTALL_RIO_VERSION=v0.6.0-alpha.x rio-test:latest
```
**Example Jenkins Shell Script:**
```
docker build -f "${WORKSPACE}/tests/Dockerfile" …
```
> Create Dockerfile for tests

- cli/cmd/up/up.go
- go.mod
- go.sum
- pkg/riofile/riofile.go
- scripts/build
- tests/integration/fixtures/riofile-with-K8s-manifests-after.yaml
- tests/integration/fixtures/riofile-with-K8s-manifests-before.yaml
- tests/integration/riofile_test.go
- tests/testutil/riofile.go
- tests/testutil/testutil.go
- vendor/github.com/rancher/wrangler/pkg/apply/apply.go
- vendor/github.com/rancher/wrangler/pkg/apply/desiredset.go
- vendor/github.com/rancher/wrangler/pkg/gvk/get.go
- vendor/modules.txt
Riofiles will modify resources
This changes modifies the apply logic to allow for a set of previously
seen GVKs to be passed into the Apply logic.
This allows for the stack to delete objects that are no longer present
in the Riofile on the next `rio up` run.
> Riofiles will modify resources

- cli/cmd/promote/promote.go
- cli/cmd/stage/stage.go
- cli/main.go
- tests/testutil/service.go
If you stage `svc@v2` and `svc@v1` has 0 spec weight, move v1 to 100 spec weight. 
Also: 
* `-e` is now ENV everywhere
* promote is two part command, does not use `@` anymore
> Stage updates orig svc weights

- scripts/build
Necessary for new build process, otherwise anyone running a mac builds a darwin CLI which fails inside rio-controller image.
> Builds CLI as linux by default

- pkg/apis/rio.cattle.io/v1/service_types.go
This alias allows for cpu values to be specified in kubernetes notation
such as "100m" without breaking the parser.
> Add mapper alias for cpu

- cli/cmd/promote/promote.go
- cli/cmd/stage/stage.go
- cli/cmd/weight/weight.go
Issue: https://github.com/rancher/rio/issues/745
Also adds check for when there are not enough steps to perform rollout on a given distance, for example 50%->51% over 2 hours would fail.
> Drop stage cattle labels and limit rollout time

- cli/cmd/config/config.go
- cli/cmd/create/create.go
- cli/cmd/create/health.go
- modules/service/controllers/service/populate/pod/containers.go
- tests/integration/run_test.go
Issue: https://github.com/rancher/rio/issues/750
Examples: 
* `rio run --health-url http://:80 -p 80 nginx`
* `rio run --health-url http://:8080/status --health-initial-delay 10s --health-interval 5s --health-failure-threshold 5 --health-timeout 5s -p 8080 cbron/mybusybox:dev`
> Fixes health-url cli and backend, improves examples

- docs/v0.6.0/publicdomain-external-services.md
Public domain and External Services v0.6.0 doc.
> Removing back quotes making the command fail when pasting in terminal

- docs/v0.6.0/riofile.md
Add an example using the kubernetes sample guestbook app to show how to
use a Riofile with additional k8s yaml. Also show how to add a
LetsEncrypt endpoint with Rio.
> Add example of using an Riofile with k8s manifests

- docs/autoscaling.md
- docs/cli-reference.md
- docs/concept.md
- docs/continuous-deployment.md
- docs/dashboard.md
- docs/developing-application-using-rio.md
- docs/faq.md
- docs/install.md
- docs/monitoring.md
- docs/publicdomain-external-services.md
- docs/quick-start.md
- docs/rbac.md
- docs/riofile.md
- docs/router.md
- docs/webhooks.md
- docs/workloads.md
- Capitalize rio > Rio where appropriate
- Capitalize kubernetes > Kubernetes where appropraite
- Capitalize docker > Docker where appropriate
- Fix capitalization of github > GitHub where appropriate
- Fix areas were articles were not utilized ("a", "an", "the") where appropriate
- Various grammar tweaks and nitpicks
> [Docs] Many small tweaks

- cli/cmd/create/create.go
- cli/cmd/promote/promote.go
- cli/cmd/ps/ps_services.go
- cli/cmd/weight/weight.go
- cli/cmd/weight/weight_test.go
- docs/cli-reference.md
- go.mod
- modules/service/controllers/rollout/controller.go
- modules/service/controllers/rollout/controller_test.go
- scripts/test
https://github.com/rancher/rio/issues/774
https://github.com/rancher/rio/issues/719
This PR does several things: 
* breaks out any tricky math into functions and unit tests them, including fixes and tests for edge cases
* fixes bug where run command wouldn't de-promote other services
* add magic so rollout is smoother
* fixed general bugs around rollout controller and weights
* updates rollout duration to 4 seconds from 2, to help avoid conflicts in api
* add note to cli and docs that rollout duration is estimation
> [0.6.x] CLI and controller updates for weights and rollouts

- cli/cmd/route/route.go
- cli/pkg/tables/router.go
- docs/cli-reference.md
Problem: if you do `rio ps` you get just `z` for `z@v0`, but if you do `rio route` then `z` means entire app not `z@v0`. What does everyone think of this solution ? 
https://github.com/rancher/rio/issues/824
> Make router app vs version ux clearer

- cli/pkg/up/build.go
- docs/riofile.md
- pkg/template/parse.go
Issue: https://github.com/rancher/rio/issues/864
1. Doesn't fallback to `Riofile` when a named riofile fails
2. Doesn't unmarshall and error a named Riofile, as non-named Riofiles don't
3. Fixes panic
4. Fixes Readme
Number 1. 
Have 2 Riofiles, one named Riofile and one named something else with different data that will fail to parse. Run `rio up -f named_file.yaml`. 
Number 2. 
Setup: save this as anything but `Riofile` and run up with `-f`, should fail to load, but it does load if named `Riofile`. Fix should allow either way. 
```
{{- if (and (eq .Values.NAMESPACE "test") (eq .Values.FOO "BAR")) }}
services:
demo:
image: ibuildthecloud/demo:v1
ports:
- 80
{{- end}}
template:
goTemplate: true # use go templating
envSubst: true # use ENV vars during templating  
questions:  # now make …
```
> Named riofiles shouldnt fallback to default riofile

- tests/Dockerfile
- tests/entrypoint.sh
- tests/scripts/cleanup_cluster.sh
- tests/scripts/entrypoint.sh
- tests/scripts/install_gke.sh
- tests/scripts/install_k3s.sh
- tests/scripts/install_rke.sh
- tests/scripts/test.sh
- tests/testutil/testutil.go
This allows going from nothing to running all rio tests on demand in a k3s cluster. Later it will be expanded for GKE and RKE clusters as well:
The first step is always to build the image: `docker build -f ./tests/Dockerfile -t rio-test .`
Then there are a few options:
- `docker run --rm -e CLUSTER=k3s -e TOKEN=<your Digital Ocean token> -e WORKERS=1 rio-test:latest`
- `docker run --rm -e test=all -e CLUSTER=k3s -e TOKEN=<your Digital Ocean token> -e AWS_ACCESS_KEY_ID=<aws access key> -e AWS_SECRET_ACCESS_KEY=<aws secret key> -e RIO_ROUTE53_ZONEID=<aws route53 zone id> -e RIO_ROUTE53_ZONENAME=<aws route53 zone name> rio-test:latest`
- Copy a kubeconfig file to /path/to/rio/.kube/config and then `docker run --rm -e test=integration rio-test:latest`
> Automate cluster creation for k3s

- cli/cmd/uninstall/uninstall.go
- go.sum
- modules/service/controllers/globalrbac/handler.go
Update the cli uninstall to delete clusterRoles and
clusterRoleBindings by the annotation
"objectset.rio.cattle.io/owner-gvk"
Add a related resource watcher to cluster scoped RBAC roles and rolebindings to watch the Rio Service for changes.
> Update uninstall to also remove RBAC objects

- README.md
- cli/cmd/buildhistory/buildhistory.go
- cli/cmd/builds/build.go
- cli/cmd/install/install.go
- cli/cmd/pods/pods.go
- cli/cmd/systemconfig/viewconfig.go
- cli/cmd/up/up.go
- cli/main.go
- cli/pkg/build/build.go
- cli/pkg/clicontext/config.go
- cli/pkg/deploymentstatus/status.go
- cli/pkg/up/build.go
- docs/cli-reference.md
- modules/rdns/controllers/service/handler.go
This commit fix bugs that clusterdomain's httpPort and httpsPort is not
being set, and start build feature on demand when user calls build
related CLI. Also add systemconfig in CLI to better view/edit feature
config.
> Fix clusterdomain for ingress, start build and add systemconfig in CLI

- tests/Dockerfile
- tests/integration/build_test.go
- tests/integration/domain_test.go
- tests/scripts/entrypoint.sh
- tests/testutil/publicdomain.go
- tests/testutil/service.go
- tests/validation/autoscale_test.go
- tests/validation/weight_test.go
This also enables building rio from master. So running the following will run all integration and validation tests in a fresh cluster:
```bash
$ docker build -f ./tests/Dockerfile -t rio-test .
$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -e test=all -e RIO_VERSION=master -e REPO=${DOCKER_USERNAME} -e TAG=dev -e CLUSTER=k3s -e TOKEN=${DigitalOcean_Token} -e WORKERS=2 -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY} -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY} -e RIO_ROUTE53_ZONEID=${ROUTE53_ZONEID} -e RIO_ROUTE53_ZONENAME=${ROUTE53_ZONENAME} rio-test:latest
```
> Fix build, domain, and validation tests

- cli/cmd/stage/stage.go
- cli/cmd/util/service.go
- tests/integration/stage_test.go
- tests/testutil/service.go
- tests/testutil/testutil.go
Issue: https://github.com/rancher/rio/issues/993
The `ListAppServicesFromServiceName` is incorrect because it won't take into account namespace-in-name, and redundant because `ListAppServicesFromAppName` gives you same data.
> cli utils bug with namespace-in-name

- modules/gloo/pkg/vsfactory/app.go
- modules/gloo/pkg/vsfactory/revision.go
- modules/gloo/pkg/vsfactory/target.go
- modules/gloo/pkg/vsfactory/vsfactory.go
Address 'no healthy upstream' by ensuring service has allocated corev1.Endpoint IP
https://github.com/rancher/rio/issues/607
https://github.com/rancher/rio/issues/584
https://github.com/rancher/rio/issues/861
> Fix 503 & 'no healthy upstream' issues

- cli/cmd/buildhistory/buildhistory.go
- cli/cmd/builds/build.go
- cli/cmd/config/config.go
- cli/cmd/externalservice/externalservice.go
- cli/cmd/publicdomain/publicdomain.go
- cli/cmd/route/route.go
- cli/cmd/secrets/secret.go
- cli/cmd/stacks/stack.go
- cli/main.go
This patch contains edits / fixes to rio help / usage system.
Beware, I am not a go programmer; I tried not to break the syntax but I do not know it nor style best practices.
Why's:
- everywhere where I encountered a $FOO or $Foo placeholder, I replaced it with FOO
- build-history - use phrase "build history" with a space in usage.
- config - specify that configmap/ must be prefixed to name. Using NAMESPACE/NAME does not work. One needs to do
- route - removed the `-n NAMESPACE` because this applies to all commands
- secret - the subcommand `ls` does not accept options nor arguments, do not state otherwise
- exec - changed CONTAINER to SERVICE because the argument is what `rio ps` displays, what seems to be called a SERVICE. The container can be specified by `-c` option
- uninstall - does …
> Edit help/usage to be more consistent and contain examples

- .gitignore
- tests/integration/config_test.go
- tests/integration/domain_test.go
- tests/integration/export_test.go
- tests/integration/externalservice_test.go
- tests/integration/log_test.go
- tests/integration/rbac_test.go
- tests/integration/run_test.go
- tests/integration/scale_test.go
- tests/integration/stage_test.go
- tests/scripts/entrypoint.sh
- tests/scripts/test.sh
- tests/testutil/externalservice.go
- tests/testutil/publicdomain.go
- tests/testutil/service.go
- tests/testutil/testutil.go
- tests/validation/domain_test.go
- Addresses all flakey tests from and resolve https://github.com/rancher/rio/issues/749
- Adds a validation test for custom cluster domain, which asserts the following:
- http and https endpoints are available on all services, whether created before or after the clusterdomain was.
- http and https custom domain endpoints retrieve the expected response
- Minor updates to how it's running the tests in docker so that Jenkins reports pass/fail correctly
> Fix remaining flakey tests and add cluster domain test

- docs/publicdomain-external-services.md
The command to unregister a public domain is `rio domain unregister`, not `rio unregister` as the document currently says.
> Fix documentation

- cli/autocomplete/bash_autocomplete
- cli/autocomplete/zsh_autocomplete
- cli/main.go
This PR enables shell completion via urfav
In order to use it, you must source the correct shell completion script
in cli/autocomplete/ with the env variable PROG=rio.
For example, 
`PROG=rio source $RIO_REPO_ROOT/cli/autocomplete/bash_autocomplete`
There is still more to be done in order to make this consumable by end
users.
> Add bash/zsh completion
